name: geojson
description: Utilities to work with geojson data. Parser with a reactive api,
  search and geofencing
homepage: https://github.com/BrightDV/geojson
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  geodesy: ^0.4.0-nullsafety.0
  geopoint:
    git: 
      url: https://github.com/BrightDV/geopoint
      ref: master
  iso:
    git: 
      url: https://github.com/BrightDV/iso
      ref: master
  pedantic: ^1.11.1

dev_dependencies:
  extra_pedantic: ^1.4.0
  test: ^1.17.4
